add: process_table.cpp
	g++ -std=c++11 -o process_data process_table.cpp -O3

debug: process_table.cpp
	g++ -D DEBUG -std=c++11 -o process_data process_table.cpp -O3

validate: process_table.cpp
	g++ -D VALIDATE -std=c++11 -o process_data process_table.cpp -O3
