add: levenshtein.cpp
	g++ -std=c++11 -o process_data levenshtein.cpp -ofast

debug: levenshtein.cpp
	g++ -D DEBUG -std=c++11 -o process_data levenshtein.cpp

validate: levenshtein.cpp
	g++ -D VALIDATE -std=c++11 -o process_data levenshtein.cpp
